class JuzData {

  List<String> JuzEnglish = [
    'Alif Laam Meem',
    'Sayaqūlu',
    'Tilka -r-rusul',
    'Lan Tana Lu',
    'W-al-muḥṣanāt',
    'Lā yuẖibbu-llāh',
    'Wa \ʾidha samiʿū',
    'Wa law \ʾannanā',
    'Qāl al-malāʾ',
    'W-a\ʿlamū',
    'Ya\ʾtadhirūna',
    'Wa mā min dābbah',
    'Wa mā \ʾubarriʾu',
    'Ruba Ma\ʾ',
    'Subḥāna -lladhi',
    'Qāla \ʾa-lam',
    'Iqtaraba li-n-nās',
    'Qad \ʾaflaḥa',
    'Wa-qāla -lladhīna',
    'Amman khalaqa',
    'Otlu maa oohiya',
    'Wa-man yaqnut',
    'Wama liya',
    'Fa-man ʾaẓlamu',
    'ʾIlaihi yuraddu',
    'Ḥā\ʾ Mīm',
    'Qāla fa-mā khatbukum',
    'Qad sami\ʿa -llāhu',
    'Tabāraka -lladhi',
     '\'Amma'
  ];

  final List<String> JuzArabic = [
    "آلم",
    "سيقول",
    "تلك الرسل",
    "لن تنالوا",
    "والمحصنات",
    "لا يحب الله",
    "وإذا سمعوا",
    "ولو أننا",
    "قال الملأ",
    "واعلموا",
    "يعتذرون",
    "ومامن دابة",
    "وما أبرئ",
    "ربما",
    "سبحٰن الذیٓ",
    "قال ألم",
    "اقترب للناس",
    "قد أفلح",
    "وقال الذين",
    "امن خلق",
    "اتل مآ اوحی",
    "ومن يقنت",
    "ومالی",
    "فمن أظلم",
    "إليه يرد",
    "حـم",
    "قال فما خطبكم",
    "قد سمع اللہ",
    "تبٰرک الذی",
    "عمّ",
  ];

}