import 'package:quran/quran.dart' as quran;

class AsmaEMuhammadData {
  List<String> names = [
    "مُحَمَّدٌ",
    "أَحْمَدٌ",
    "حَامِدٌ",
    "مَحمُودٌ",
    "قَاسِمٌ",
    "عَاقِبٌ",
    "فَاتِحٌ",
    "شَاهِدٌ",
    "حَاشِرٌ",
    "رَشِیدٌ",
    "مَشهُودٌ",
    "بَشِیرٌ",
    "نَزِیرٌ",
    "دَاعٍ",
    "شَافٍ",
    "ھَادٍ",
    "مَھدٍ",
    "مَاحٍ",
    "مُنجٍ",
    "نَاهٍ",
    "رَسُولٌ",
    "نَبِىٌ",
    "اُمِّىٌ",
    "تِهَامِىٌ",
    "هَاشَمِىٌ",
    "اَبطَحِىٌ",
    "عَزِيزٌ",
    "حَرِيصٌ عَلَيكُم",
    "رَؤُف",
    "رَحِيمٌ",
    "طٰهٰ",
    "مُجتَبىٰ",
    "طٰسٓ",
    "مُرتَضیٰ",
    "حٰمٓ",
    "مُصطَفىٰ",
    "يٰسٓ",
    "اَولىٰ",
    "مُزَّمِلٌ",
    "وَلِىٌ",
    "مُدَّثِّرٌ",
    "مَتِينٌ",
    "مُصَدِّقٌ",
    "طَيِّبٌ",
    "نَاصِرٌ",
    "مَنصُورٌ",
    "مِصبَاحٌ",
    "اٰمِرٌ",
    "حِجَازِىٌ",
    "نَزَارِىٌ",
    "قُرَیشِی",
    "مُضَرِىٌ",
    "نَبِیُّ التَّوبَۃ",
    "حَافِظٌ",
    "كَامِلٌ",
    "صَادِقٌ",
    "اَمِينٌ",
    "عَبدُاللّٰه",
    "كَلِيمُ اللّٰه",
    "حَبِیبُ اللّٰه",
    "نَجِیُّ اللّٰه",
    "صَفِیُّ اللّٰه",
    "خَاتِمُ الانَبِيآء",
    "حَسِيبٌ",
    "مُجِيبٌ",
    "شَكُورٌ",
    "مُقتَصِدٌ",
    "رَسُولُ الرَّحمَةِ",
    "قَوِىٌ",
    "حَفِىٌ",
    "مَامُونٌ",
    "مَعلُومٌ",
    "حَقٌ",
    "مُبِينٌ",
    "مُطِيعٌ",
    "اَوَّلٌ",
    "اٰخِرٌ",
    "ظَاهِرٌ",
    "بَاطِنٌ",
    "يَتِيمٌ",
    "كَرِيمٌ",
    "حَكِيمٌ",
    "سَيِّدٌ",
    "سِرَاجٌ",
    "مُنِيرٌ",
    "مُحَرَّمٌ",
    "مُكَرَّمٌ",
    "مُبَشِرٌ",
    "مُزَكِّرٌ",
    "مُطَهَّرٌ",
    "قَريِبٌ",
    "خَلِيلٌ",
    "مَدعُوٌ",
    "جَوَّادٌ",
    "خَاتِمٌ",
    "عَادِلٌ",
    "شَھِیر",
    "شَھِید",
    "رَسُولُ المَلاَحِم"
  ];

  List<String> englishNames = [
    "Muhammad",
    "Ahmad",
    "Haamid",
    "Mahmud",
    "Qaasim",
    "Aqib",
    "Faateh",
    "Shahid",
    "Hashir",
    "Rasheed",
    "Mashhood",
    "Basheer",
    "Nadhir",
    "Dai",
    "Shafi",
    "Haad",
    "Mahd",
    "Maah",
    "Munji",
    "Nahi",
    "Rasul",
    "Nabi",
    "Ummi",
    "Tihami",
    "Hashami",
    "Abtahi",
    "Aziz",
    "Haris Alaikum",
    "Rauf",
    "Rahim",
    "Taha",
    "Mujtaba",
    "Tasin",
    "Murtada",
    "Ha-mim",
    "Mustafa",
    "Ya-sin",
    "Aula",
    "Muzamil",
    "Wali",
    "Mudaththir",
    "Matin",
    "Musaddiq",
    "Tayyab",
    "Nasir",
    "Mansoor",
    "Misbah",
    "Amir",
    "Hijazi",
    "Nazaari",
    "Quraishi",
    "Mudari",
    "Nabi-at-tauba",
    "Hafiz",
    "Kamil",
    "Sadiq",
    "Amin",
    "Abdullah",
    "Kalim Allah",
    "Habib Allah",
    "Naji Allah",
    "Safi Allah",
    "Khatam Ul-Anbia",
    "Hasib",
    "Mujib",
    "Shakoor",
    "Muqtasid",
    "Rasul al-rahmah",
    "Qawi",
    "Hafi",
    "Mamoon",
    "Ma'lum",
    "Haqq",
    "Mubeen",
    "Mutti",
    "Awwal",
    "Akhir",
    "Zahir",
    "Batin",
    "Yateem",
    "Karim",
    "Hakim",
    "Sayyad",
    "Siraj",
    "Munir",
    "Muharram",
    "Mukarram",
    "Mubashshir",
    "Mudakir",
    "Mutahhar",
    "Qareeb",
    "Khalil",
    "Mad'u",
    "Jawwad",
    "Khatim",
    "Adil",
    "Shahir",
    "Shaheed",
    "Rasul al-malahim",
  ];

  List<String> meaning = [
    "Highly Praised",
    "The Most Commendable",
    "Praising",
    "Praised",
    "The father of Qasim",
    "The Latest",
    "The Victor",
    "The Witness",
    "The Awakener, The Gatherer",
    "The Guide",
    "He who is witnessed",
    "The Messenger of Good News",
    "Wamer",
    "The Caller",
    "Healer",
    "The Leader",
    "The Guided One",
    "The obliterator of Infidelity",
    "He who saves delivers",
    "Safe",
    "Messenger",
    "Prophet",
    "Unlettered",
    "From the Tihama",
    "Family of Hashim",
    "Belonging to al-Batha",
    "Nobel, Dear",
    "Full of concern for you",
    "Mild",
    "Merciful",
    "Surah 20:13",
    "Elect",
    "Surah 27:13",
    "Content",
    "Binging of surah 40:46",
    "Chosen",
    "Surah 36:13",
    "Worthier, most worthy",
    "Wrapped",
    "Friend",
    "Covered",
    "Firm",
    "Who declares for true",
    "Good",
    "Helper",
    "Helped (by God)",
    "Lamp",
    "Prince, commander",
    "From the Hijaz",
    "Of nazareth",
    "From the Clan quraish",
    "From the trib mudar",
    "The Prophet of Repentance",
    "Preserver",
    "Perfect",
    "Sincere",
    "Trustworthy",
    "God's servant",
    "He to whom God has Talked",
    "God's beloved friend",
    "God's Intimate friend",
    "God's sincere friend",
    "Seal of the Prophet",
    "Respected",
    "Comping, Relying",
    "Most grateful",
    "Adopting a middle course",
    "The Messenger of mercy",
    "Strong",
    "Wel-Informed",
    "Trusted",
    "wel-known",
    "Truth",
    "Clear,Evident",
    "Obident",
    "The First",
    "Last",
    "Evident",
    "Inner",
    "Orphan",
    "Generous",
    "Wise",
    "Master",
    "Lamp",
    "Radiant",
    "Forbiden",
    "Honored, Venerated",
    "Bringer of Good News",
    "Reminder",
    "Purified",
    "Near",
    "Good Friend",
    "Who Is Called",
    "Generous",
    "Seal",
    "Justic",
    "Well-Known",
    "Witness",
    "The Messenger of the Battles of Last Day",
  ];
}
